[2024-12-29T04:30:47.944+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-29T04:30:48.046+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_pipeline.scrape_filmmakers scheduled__2024-12-28T00:00:00+00:00 [queued]>
[2024-12-29T04:30:48.481+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_pipeline.scrape_filmmakers scheduled__2024-12-28T00:00:00+00:00 [queued]>
[2024-12-29T04:30:48.488+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 1
[2024-12-29T04:30:48.537+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_filmmakers> on 2024-12-28 00:00:00+00:00
[2024-12-29T04:30:48.556+0000] {standard_task_runner.py:72} INFO - Started process 199 to run task
[2024-12-29T04:30:48.573+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'movie_pipeline', 'scrape_filmmakers', 'scheduled__2024-12-28T00:00:00+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmp8a3dfikz']
[2024-12-29T04:30:48.582+0000] {standard_task_runner.py:105} INFO - Job 114: Subtask scrape_filmmakers
[2024-12-29T04:30:48.874+0000] {task_command.py:467} INFO - Running <TaskInstance: movie_pipeline.scrape_filmmakers scheduled__2024-12-28T00:00:00+00:00 [running]> on host e0a3add0f1ca
[2024-12-29T04:30:49.604+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie_pipeline' AIRFLOW_CTX_TASK_ID='scrape_filmmakers' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-28T00:00:00+00:00'
[2024-12-29T04:30:49.610+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-29T04:30:51.958+0000] {extract.py:152} INFO - movie iteration 0 and filmamker iteration 0 for movie_id : tt13186482 and filmmaker_id: nm1503575
[2024-12-29T04:31:46.643+0000] {extract.py:152} INFO - movie iteration 0 and filmamker iteration 1 for movie_id : tt13186482 and filmmaker_id: nm0622288
[2024-12-29T04:32:17.213+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-12-29T04:32:17.307+0000] {process_utils.py:132} INFO - Sending 15 to group 199. PIDs of all processes in the group: [263, 299, 307, 308, 336, 338, 407, 381, 435, 559, 750, 405, 199]
[2024-12-29T04:32:17.315+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 199
[2024-12-29T04:32:17.339+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-29T04:32:17.426+0000] {connectionpool.py:827} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0509547d30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6269b1707dedcbbebcb124182e483e78/window
