[2024-12-21T10:24:18.681+0530] {processor.py:186} INFO - Started process (PID=2376) to work on /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T10:24:18.683+0530] {processor.py:914} INFO - Processing file /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-21T10:24:18.685+0530] {logging_mixin.py:190} INFO - [2024-12-21T10:24:18.685+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T10:24:18.761+0530] {logging_mixin.py:190} INFO - [2024-12-21T10:24:18.760+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-21T10:24:18.761+0530] {logging_mixin.py:190} INFO - [2024-12-21T10:24:18.761+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-21T10:24:18.763+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T10:24:19.202+0530] {processor.py:208} INFO - Processing /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.530 seconds
[2024-12-21T10:26:26.989+0530] {processor.py:186} INFO - Started process (PID=2691) to work on /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T10:26:26.990+0530] {processor.py:914} INFO - Processing file /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-21T10:26:26.992+0530] {logging_mixin.py:190} INFO - [2024-12-21T10:26:26.992+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T10:26:27.035+0530] {logging_mixin.py:190} INFO - [2024-12-21T10:26:27.035+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-21T10:26:27.036+0530] {logging_mixin.py:190} INFO - [2024-12-21T10:26:27.036+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-21T10:26:27.036+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T10:26:27.225+0530] {processor.py:208} INFO - Processing /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.243 seconds
[2024-12-21T10:29:00.819+0530] {processor.py:186} INFO - Started process (PID=3113) to work on /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T10:29:00.821+0530] {processor.py:914} INFO - Processing file /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-21T10:29:00.825+0530] {logging_mixin.py:190} INFO - [2024-12-21T10:29:00.824+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T10:29:00.895+0530] {logging_mixin.py:190} INFO - [2024-12-21T10:29:00.894+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-21T10:29:00.896+0530] {logging_mixin.py:190} INFO - [2024-12-21T10:29:00.895+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-21T10:29:00.899+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T10:29:01.125+0530] {processor.py:208} INFO - Processing /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.317 seconds
[2024-12-21T10:48:37.533+0530] {processor.py:186} INFO - Started process (PID=4235) to work on /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T10:48:37.535+0530] {processor.py:914} INFO - Processing file /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-21T10:48:37.537+0530] {logging_mixin.py:190} INFO - [2024-12-21T10:48:37.537+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T10:48:37.588+0530] {logging_mixin.py:190} INFO - [2024-12-21T10:48:37.587+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-21T10:48:37.588+0530] {logging_mixin.py:190} INFO - [2024-12-21T10:48:37.588+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-21T10:48:37.589+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T10:48:37.790+0530] {processor.py:208} INFO - Processing /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.263 seconds
[2024-12-21T10:51:00.747+0530] {processor.py:186} INFO - Started process (PID=4710) to work on /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T10:51:00.749+0530] {processor.py:914} INFO - Processing file /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-21T10:51:00.753+0530] {logging_mixin.py:190} INFO - [2024-12-21T10:51:00.752+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T10:51:00.804+0530] {logging_mixin.py:190} INFO - [2024-12-21T10:51:00.803+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-21T10:51:00.804+0530] {logging_mixin.py:190} INFO - [2024-12-21T10:51:00.804+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-21T10:51:00.805+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T10:51:01.097+0530] {processor.py:208} INFO - Processing /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.355 seconds
[2024-12-21T11:55:48.700+0530] {processor.py:186} INFO - Started process (PID=6764) to work on /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T11:55:48.702+0530] {processor.py:914} INFO - Processing file /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-21T11:55:48.704+0530] {logging_mixin.py:190} INFO - [2024-12-21T11:55:48.704+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T11:55:48.774+0530] {logging_mixin.py:190} INFO - [2024-12-21T11:55:48.773+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-21T11:55:48.775+0530] {logging_mixin.py:190} INFO - [2024-12-21T11:55:48.774+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-21T11:55:48.775+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T11:55:49.024+0530] {processor.py:208} INFO - Processing /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.330 seconds
[2024-12-21T11:58:00.779+0530] {processor.py:186} INFO - Started process (PID=7234) to work on /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T11:58:00.783+0530] {processor.py:914} INFO - Processing file /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-21T11:58:00.784+0530] {logging_mixin.py:190} INFO - [2024-12-21T11:58:00.784+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T11:58:00.834+0530] {logging_mixin.py:190} INFO - [2024-12-21T11:58:00.833+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-21T11:58:00.834+0530] {logging_mixin.py:190} INFO - [2024-12-21T11:58:00.834+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-21T11:58:00.834+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T11:58:01.072+0530] {processor.py:208} INFO - Processing /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.298 seconds
[2024-12-21T12:01:13.859+0530] {processor.py:186} INFO - Started process (PID=7923) to work on /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T12:01:13.861+0530] {processor.py:914} INFO - Processing file /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-21T12:01:13.866+0530] {logging_mixin.py:190} INFO - [2024-12-21T12:01:13.865+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T12:01:13.948+0530] {logging_mixin.py:190} INFO - [2024-12-21T12:01:13.948+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-21T12:01:13.949+0530] {logging_mixin.py:190} INFO - [2024-12-21T12:01:13.948+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-21T12:01:13.949+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T12:01:14.232+0530] {processor.py:208} INFO - Processing /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.381 seconds
[2024-12-21T12:04:51.646+0530] {processor.py:186} INFO - Started process (PID=8673) to work on /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T12:04:51.650+0530] {processor.py:914} INFO - Processing file /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-21T12:04:51.653+0530] {logging_mixin.py:190} INFO - [2024-12-21T12:04:51.653+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T12:04:51.711+0530] {logging_mixin.py:190} INFO - [2024-12-21T12:04:51.710+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-21T12:04:51.712+0530] {logging_mixin.py:190} INFO - [2024-12-21T12:04:51.711+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-21T12:04:51.712+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T12:04:51.979+0530] {processor.py:208} INFO - Processing /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.339 seconds
[2024-12-21T22:32:19.082+0530] {processor.py:186} INFO - Started process (PID=15987) to work on /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T22:32:19.085+0530] {processor.py:914} INFO - Processing file /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-21T22:32:19.091+0530] {logging_mixin.py:190} INFO - [2024-12-21T22:32:19.090+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T22:32:19.102+0530] {logging_mixin.py:190} INFO - [2024-12-21T22:32:19.099+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-21T22:32:19.104+0530] {logging_mixin.py:190} INFO - [2024-12-21T22:32:19.103+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-21T22:32:19.105+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T22:32:19.165+0530] {processor.py:208} INFO - Processing /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2024-12-21T22:32:53.306+0530] {processor.py:186} INFO - Started process (PID=16228) to work on /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T22:32:53.309+0530] {processor.py:914} INFO - Processing file /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-21T22:32:53.316+0530] {logging_mixin.py:190} INFO - [2024-12-21T22:32:53.315+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T22:32:53.328+0530] {logging_mixin.py:190} INFO - [2024-12-21T22:32:53.326+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-21T22:32:53.329+0530] {logging_mixin.py:190} INFO - [2024-12-21T22:32:53.328+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-21T22:32:53.331+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T22:32:53.411+0530] {processor.py:208} INFO - Processing /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.123 seconds
[2024-12-21T22:33:23.967+0530] {processor.py:186} INFO - Started process (PID=16429) to work on /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T22:33:23.970+0530] {processor.py:914} INFO - Processing file /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-21T22:33:23.976+0530] {logging_mixin.py:190} INFO - [2024-12-21T22:33:23.976+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T22:33:23.985+0530] {logging_mixin.py:190} INFO - [2024-12-21T22:33:23.983+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-21T22:33:23.986+0530] {logging_mixin.py:190} INFO - [2024-12-21T22:33:23.985+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-21T22:33:23.987+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T22:33:24.046+0530] {processor.py:208} INFO - Processing /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2024-12-21T23:53:02.224+0530] {processor.py:186} INFO - Started process (PID=18110) to work on /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T23:53:02.228+0530] {processor.py:914} INFO - Processing file /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-21T23:53:02.237+0530] {logging_mixin.py:190} INFO - [2024-12-21T23:53:02.236+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T23:53:02.250+0530] {logging_mixin.py:190} INFO - [2024-12-21T23:53:02.248+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-21T23:53:02.253+0530] {logging_mixin.py:190} INFO - [2024-12-21T23:53:02.252+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-21T23:53:02.255+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T23:53:02.462+0530] {processor.py:208} INFO - Processing /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.260 seconds
[2024-12-21T23:53:33.305+0530] {processor.py:186} INFO - Started process (PID=18323) to work on /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T23:53:33.308+0530] {processor.py:914} INFO - Processing file /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-21T23:53:33.314+0530] {logging_mixin.py:190} INFO - [2024-12-21T23:53:33.313+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T23:53:33.324+0530] {logging_mixin.py:190} INFO - [2024-12-21T23:53:33.322+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-21T23:53:33.325+0530] {logging_mixin.py:190} INFO - [2024-12-21T23:53:33.325+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-21T23:53:33.326+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-21T23:53:33.394+0530] {processor.py:208} INFO - Processing /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.196 seconds
