[2025-01-08T17:08:53.443+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-08T17:08:53.624+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_pipeline.scrape_collection_page manual__2025-01-08T17:08:42.524834+00:00 [queued]>
[2025-01-08T17:08:53.696+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_pipeline.scrape_collection_page manual__2025-01-08T17:08:42.524834+00:00 [queued]>
[2025-01-08T17:08:53.698+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-08T17:08:53.792+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_collection_page> on 2025-01-08 17:08:42.524834+00:00
[2025-01-08T17:08:53.821+0000] {standard_task_runner.py:72} INFO - Started process 236 to run task
[2025-01-08T17:08:53.862+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'movie_pipeline', 'scrape_collection_page', 'manual__2025-01-08T17:08:42.524834+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmp11i4ycq0']
[2025-01-08T17:08:53.981+0000] {standard_task_runner.py:105} INFO - Job 123: Subtask scrape_collection_page
[2025-01-08T17:08:54.578+0000] {task_command.py:467} INFO - Running <TaskInstance: movie_pipeline.scrape_collection_page manual__2025-01-08T17:08:42.524834+00:00 [running]> on host d92005d21524
[2025-01-08T17:08:55.030+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie_pipeline' AIRFLOW_CTX_TASK_ID='scrape_collection_page' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T17:08:42.524834+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-08T17:08:42.524834+00:00'
[2025-01-08T17:08:55.034+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-08T17:09:09.918+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-01-08T17:09:09.926+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-08T17:09:09.939+0000] {process_utils.py:132} INFO - Sending 15 to group 236. PIDs of all processes in the group: [271, 277, 281, 282, 292, 293, 295, 314, 236]
[2025-01-08T17:09:09.943+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 236
[2025-01-08T17:09:09.947+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-08T17:09:09.989+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=314, status='terminated', started='17:09:08') (314) terminated with exit code None
[2025-01-08T17:09:10.274+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=293, status='terminated', started='17:09:05') (293) terminated with exit code None
[2025-01-08T17:09:10.378+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-08T17:09:10.556+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=271, status='terminated', started='17:09:04') (271) terminated with exit code None
[2025-01-08T17:09:10.702+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=295, status='terminated', started='17:09:06') (295) terminated with exit code None
[2025-01-08T17:09:10.706+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=236, status='terminated', exitcode=0, started='17:08:52') (236) terminated with exit code 0
[2025-01-08T17:09:12.006+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=277, status='terminated', started='17:09:04') (277) terminated with exit code None
[2025-01-08T17:09:12.008+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=281, status='terminated', started='17:09:04') (281) terminated with exit code None
[2025-01-08T17:09:12.014+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=292, status='terminated', started='17:09:05') (292) terminated with exit code None
[2025-01-08T17:09:12.016+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=282, status='terminated', started='17:09:04') (282) terminated with exit code None
