[2024-12-28T13:19:56.049+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-28T13:20:11.520+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_pipeline.parse_filmmakers manual__2024-12-27T11:38:32.797674+00:00 [queued]>
[2024-12-28T13:20:11.727+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_pipeline.parse_filmmakers manual__2024-12-27T11:38:32.797674+00:00 [queued]>
[2024-12-28T13:20:11.765+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-28T13:20:12.012+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): parse_filmmakers> on 2024-12-27 11:38:32.797674+00:00
[2024-12-28T13:20:12.138+0000] {standard_task_runner.py:72} INFO - Started process 5672 to run task
[2024-12-28T13:20:12.232+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'movie_pipeline', 'parse_filmmakers', 'manual__2024-12-27T11:38:32.797674+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpdwcyxylg']
[2024-12-28T13:20:12.460+0000] {standard_task_runner.py:105} INFO - Job 95: Subtask parse_filmmakers
[2024-12-28T13:20:13.985+0000] {task_command.py:467} INFO - Running <TaskInstance: movie_pipeline.parse_filmmakers manual__2024-12-27T11:38:32.797674+00:00 [running]> on host e0a3add0f1ca
[2024-12-28T13:20:20.593+0000] {job.py:229} INFO - Heartbeat recovered after 31.83 seconds
[2024-12-28T13:20:23.087+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie_pipeline' AIRFLOW_CTX_TASK_ID='parse_filmmakers' AIRFLOW_CTX_EXECUTION_DATE='2024-12-27T11:38:32.797674+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-27T11:38:32.797674+00:00'
[2024-12-28T13:20:23.164+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-28T13:21:40.525+0000] {parse.py:413} INFO - Iteration: 0
[2024-12-28T13:22:14.875+0000] {parse.py:413} INFO - Iteration: 1
[2024-12-28T13:22:19.660+0000] {parse.py:413} INFO - Iteration: 2
[2024-12-28T13:22:23.956+0000] {parse.py:413} INFO - Iteration: 3
[2024-12-28T13:22:28.266+0000] {parse.py:413} INFO - Iteration: 4
[2024-12-28T13:22:30.745+0000] {parse.py:413} INFO - Iteration: 5
[2024-12-28T13:22:33.828+0000] {parse.py:413} INFO - Iteration: 6
[2024-12-28T13:22:45.687+0000] {parse.py:413} INFO - Iteration: 7
[2024-12-28T13:22:51.080+0000] {parse.py:413} INFO - Iteration: 8
[2024-12-28T13:22:54.514+0000] {parse.py:413} INFO - Iteration: 9
[2024-12-28T13:22:57.668+0000] {parse.py:413} INFO - Iteration: 10
[2024-12-28T13:23:01.549+0000] {parse.py:413} INFO - Iteration: 11
[2024-12-28T13:23:03.483+0000] {parse.py:413} INFO - Iteration: 12
[2024-12-28T13:23:06.468+0000] {parse.py:413} INFO - Iteration: 13
[2024-12-28T13:23:11.240+0000] {parse.py:413} INFO - Iteration: 14
[2024-12-28T13:23:18.765+0000] {parse.py:413} INFO - Iteration: 15
[2024-12-28T13:23:25.585+0000] {parse.py:413} INFO - Iteration: 16
[2024-12-28T13:23:29.544+0000] {parse.py:413} INFO - Iteration: 17
[2024-12-28T13:23:31.497+0000] {parse.py:449} ERROR - 'NoneType' object has no attribute 'select'
Traceback (most recent call last):
  File "/opt/src/parse.py", line 447, in filmmaker_parser
    filmmaker_birth_details=soup_profile.find('li',attrs={'data-testid':'nm_pd_bl'}).select("div>ul>li")
AttributeError: 'NoneType' object has no attribute 'select'
[2024-12-28T13:23:31.545+0000] {parse.py:473} WARNING - filmmaker_dict['dob'] set to NONE
[2024-12-28T13:23:31.550+0000] {parse.py:475} WARNING - filmmaker_dict['place_of_birth'] set to NONE
[2024-12-28T13:23:31.556+0000] {parse.py:477} WARNING - filmmaker_dict['country'] set to NONE
[2024-12-28T13:23:31.919+0000] {parse.py:413} INFO - Iteration: 18
[2024-12-28T13:23:36.155+0000] {parse.py:413} INFO - Iteration: 19
[2024-12-28T13:23:40.451+0000] {parse.py:413} INFO - Iteration: 20
[2024-12-28T13:23:43.173+0000] {parse.py:413} INFO - Iteration: 21
[2024-12-28T13:23:46.412+0000] {parse.py:413} INFO - Iteration: 22
[2024-12-28T13:23:49.551+0000] {parse.py:413} INFO - Iteration: 23
[2024-12-28T13:23:51.579+0000] {parse.py:413} INFO - Iteration: 24
[2024-12-28T13:23:53.189+0000] {parse.py:449} ERROR - 'NoneType' object has no attribute 'select'
Traceback (most recent call last):
  File "/opt/src/parse.py", line 447, in filmmaker_parser
    filmmaker_birth_details=soup_profile.find('li',attrs={'data-testid':'nm_pd_bl'}).select("div>ul>li")
AttributeError: 'NoneType' object has no attribute 'select'
[2024-12-28T13:23:53.190+0000] {parse.py:473} WARNING - filmmaker_dict['dob'] set to NONE
[2024-12-28T13:23:53.191+0000] {parse.py:475} WARNING - filmmaker_dict['place_of_birth'] set to NONE
[2024-12-28T13:23:53.193+0000] {parse.py:477} WARNING - filmmaker_dict['country'] set to NONE
[2024-12-28T13:23:53.307+0000] {parse.py:413} INFO - Iteration: 25
[2024-12-28T13:23:55.719+0000] {parse.py:413} INFO - Iteration: 26
[2024-12-28T13:23:58.642+0000] {parse.py:413} INFO - Iteration: 27
[2024-12-28T13:24:03.353+0000] {parse.py:413} INFO - Iteration: 28
[2024-12-28T13:24:05.732+0000] {parse.py:413} INFO - Iteration: 29
[2024-12-28T13:24:07.138+0000] {parse.py:413} INFO - Iteration: 30
[2024-12-28T13:24:10.289+0000] {parse.py:413} INFO - Iteration: 31
[2024-12-28T13:24:12.729+0000] {parse.py:413} INFO - Iteration: 32
[2024-12-28T13:24:14.821+0000] {parse.py:413} INFO - Iteration: 33
[2024-12-28T13:24:16.567+0000] {parse.py:413} INFO - Iteration: 34
[2024-12-28T13:24:19.539+0000] {parse.py:413} INFO - Iteration: 35
[2024-12-28T13:24:21.796+0000] {parse.py:413} INFO - Iteration: 36
[2024-12-28T13:24:23.463+0000] {parse.py:449} ERROR - 'NoneType' object has no attribute 'select'
Traceback (most recent call last):
  File "/opt/src/parse.py", line 447, in filmmaker_parser
    filmmaker_birth_details=soup_profile.find('li',attrs={'data-testid':'nm_pd_bl'}).select("div>ul>li")
AttributeError: 'NoneType' object has no attribute 'select'
[2024-12-28T13:24:23.465+0000] {parse.py:473} WARNING - filmmaker_dict['dob'] set to NONE
[2024-12-28T13:24:23.470+0000] {parse.py:475} WARNING - filmmaker_dict['place_of_birth'] set to NONE
[2024-12-28T13:24:23.473+0000] {parse.py:477} WARNING - filmmaker_dict['country'] set to NONE
[2024-12-28T13:24:23.593+0000] {parse.py:413} INFO - Iteration: 37
[2024-12-28T13:24:25.221+0000] {parse.py:413} INFO - Iteration: 38
[2024-12-28T13:24:26.638+0000] {parse.py:413} INFO - Iteration: 39
[2024-12-28T13:24:28.062+0000] {parse.py:413} INFO - Iteration: 40
[2024-12-28T13:24:29.458+0000] {parse.py:457} ERROR - time data 'Australia' does not match format '%B %d, %Y'
Traceback (most recent call last):
  File "/opt/src/parse.py", line 455, in filmmaker_parser
    filmmaker_dict['dob']=str(datetime.strptime(dob,"%B %d, %Y").date())
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Australia' does not match format '%B %d, %Y'
[2024-12-28T13:24:29.462+0000] {parse.py:459} WARNING - filmmaker_dict['dob'] set to NONE
[2024-12-28T13:24:29.465+0000] {parse.py:466} ERROR - list index out of range
Traceback (most recent call last):
  File "/opt/src/parse.py", line 461, in filmmaker_parser
    location=filmmaker_birth_details[1].text
IndexError: list index out of range
[2024-12-28T13:24:29.470+0000] {parse.py:468} WARNING - filmmaker_dict['place_of_birth'] set to NONE
[2024-12-28T13:24:29.472+0000] {parse.py:470} WARNING - filmmaker_dict['country'] set to NONE
[2024-12-28T13:24:29.575+0000] {parse.py:413} INFO - Iteration: 41
[2024-12-28T13:24:31.576+0000] {parse.py:413} INFO - Iteration: 42
[2024-12-28T13:24:34.954+0000] {parse.py:413} INFO - Iteration: 43
[2024-12-28T13:24:37.065+0000] {parse.py:466} ERROR - list index out of range
Traceback (most recent call last):
  File "/opt/src/parse.py", line 461, in filmmaker_parser
    location=filmmaker_birth_details[1].text
IndexError: list index out of range
[2024-12-28T13:24:37.067+0000] {parse.py:468} WARNING - filmmaker_dict['place_of_birth'] set to NONE
[2024-12-28T13:24:37.068+0000] {parse.py:470} WARNING - filmmaker_dict['country'] set to NONE
[2024-12-28T13:24:37.396+0000] {parse.py:413} INFO - Iteration: 44
[2024-12-28T13:24:40.921+0000] {parse.py:457} ERROR - time data 'April 27' does not match format '%B %d, %Y'
Traceback (most recent call last):
  File "/opt/src/parse.py", line 455, in filmmaker_parser
    filmmaker_dict['dob']=str(datetime.strptime(dob,"%B %d, %Y").date())
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'April 27' does not match format '%B %d, %Y'
[2024-12-28T13:24:40.923+0000] {parse.py:459} WARNING - filmmaker_dict['dob'] set to NONE
[2024-12-28T13:24:41.010+0000] {parse.py:413} INFO - Iteration: 45
[2024-12-28T13:24:42.868+0000] {parse.py:413} INFO - Iteration: 46
[2024-12-28T13:24:44.166+0000] {parse.py:457} ERROR - time data 'January 8' does not match format '%B %d, %Y'
Traceback (most recent call last):
  File "/opt/src/parse.py", line 455, in filmmaker_parser
    filmmaker_dict['dob']=str(datetime.strptime(dob,"%B %d, %Y").date())
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'January 8' does not match format '%B %d, %Y'
[2024-12-28T13:24:44.168+0000] {parse.py:459} WARNING - filmmaker_dict['dob'] set to NONE
[2024-12-28T13:24:44.282+0000] {parse.py:413} INFO - Iteration: 47
[2024-12-28T13:24:46.485+0000] {parse.py:413} INFO - Iteration: 48
[2024-12-28T13:24:48.003+0000] {parse.py:449} ERROR - 'NoneType' object has no attribute 'select'
Traceback (most recent call last):
  File "/opt/src/parse.py", line 447, in filmmaker_parser
    filmmaker_birth_details=soup_profile.find('li',attrs={'data-testid':'nm_pd_bl'}).select("div>ul>li")
AttributeError: 'NoneType' object has no attribute 'select'
[2024-12-28T13:24:48.010+0000] {parse.py:473} WARNING - filmmaker_dict['dob'] set to NONE
[2024-12-28T13:24:48.016+0000] {parse.py:475} WARNING - filmmaker_dict['place_of_birth'] set to NONE
[2024-12-28T13:24:48.018+0000] {parse.py:477} WARNING - filmmaker_dict['country'] set to NONE
[2024-12-28T13:24:48.333+0000] {parse.py:413} INFO - Iteration: 49
[2024-12-28T13:24:51.635+0000] {parse.py:413} INFO - Iteration: 50
[2024-12-28T13:24:54.322+0000] {parse.py:413} INFO - Iteration: 51
[2024-12-28T13:24:57.524+0000] {parse.py:413} INFO - Iteration: 52
[2024-12-28T13:24:59.589+0000] {parse.py:413} INFO - Iteration: 53
[2024-12-28T13:25:02.307+0000] {python.py:240} INFO - Done. Returned value was: run_20241225/filmmaker_parsed_20241225.json
[2024-12-28T13:25:02.586+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-28T13:25:02.588+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=movie_pipeline, task_id=parse_filmmakers, run_id=manual__2024-12-27T11:38:32.797674+00:00, execution_date=20241227T113832, start_date=20241228T132011, end_date=20241228T132502
[2024-12-28T13:25:02.846+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-28T13:25:03.046+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-12-28T13:25:03.133+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-28T13:25:03.188+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
